import type { Metadata } from 'next'

import { DashboardNavBar } from '@/components/dashboardNavBar/DashboardNavbar'

import { Header } from '../../components/header/header'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<div>
			<Header />
			<div className='flex'>
				<DashboardNavBar />
				{children}
			</div>
		</div>
	)
}
